class ViewsMenuScreen
  include Gametel

  list_item(:animation, :text => 'Animation')
  list_item(:auto_complete, :text => 'Auto Complete')
  list_item(:buttons, :text => 'Buttons')
  list_item(:chronometer, :text => 'Chronometer')
  list_item(:controls, :text => 'Controls')
  list_item(:custom, :text => 'Custom')
  list_item(:date_widgets, :text => 'Date Widgets')
  list_item(:expandable_lists, :text => 'Expandable Lists')
  list_item(:focus, :text => 'Focus')
  list_item(:full_screen_modes, :text => 'Full Screen Modes')
  list_item(:gallery, :text => 'Gallery')
  list_item(:game_controller_input, :text => 'Game Controller Input')
  list_item(:grid, :text => 'Grid')
  list_item(:hover_events, :text => 'Hover Events')
  list_item(:image_button, :text => 'ImageButton')
  list_item(:image_switcher, :text => 'ImageSwitcher')
  list_item(:image_view, :text => 'ImageView')
  list_item(:layout_animations, :text => 'Layout Animations')
  list_item(:layouts, :text => 'Layouts')
  list_item(:lists, :text => '^Lists$')
  list_item(:popup_menu, :text => 'Popup Menu')
  list_item(:progress_bar, :text => 'Progress Bar')
  list_item(:radio_group, :text => 'Radio Group')
  list_item(:rating_bar, :text => 'Rating Bar')
  list_item(:rotating_button, :text => 'Rotating Button')
  list_item(:scrollbars, :text => 'ScrollBars')
  list_item(:search_view, :text => 'Search View')
  list_item(:secure_view, :text => 'Secure View')
  list_item(:seek_bar, :text => 'Seek Bar')
  list_item(:spinner, :text => 'Spinner')
  list_item(:splitting_touches_across_views, :text => 'Splitting Touches across Views')
  list_item(:switches, :text => 'Switches')
  list_item(:tabs, :text => 'Tabs')
  list_item(:text_switcher, :text => 'TextSwitcher')
  list_item(:visibility, :text => 'Visibility')
  list_item(:webview, :text => 'WebView')
end
