class ViewsMenuScreen
  include Gametel

  list_item(:animation, :index => 0)
  list_item(:auto_complete, :index => 1)
  list_item(:buttons, :index => 2)
  list_item(:chronometer, :index => 3)
  list_item(:controls, :index => 4)
  list_item(:custom, :index => 5)
  list_item(:date_widgets, :index => 6)
  list_item(:drag_and_drop, :index => 7)
  list_item(:expandable_lists, :index => 8)
  list_item(:focus, :index => 9)
  list_item(:full_screen_modes, :index => 10)
  list_item(:gallery, :index => 11)
  list_item(:game_controller_input, :index => 12)
  list_item(:grid, :index => 13)
  list_item(:hover_events, :index => 14)
  list_item(:image_button, :index => 15)
  list_item(:image_switcher, :index => 16)
  list_item(:image_view, :index => 17)
  list_item(:layout_animations, :index => 18)
  list_item(:layouts, :index => 19)
  list_item(:lists, :index => 20)
  list_item(:popup_menu, :index => 21)
  list_item(:progress_bar, :index => 22)
  list_item(:radio_group, :index => 23)
  list_item(:rating_bar, :index => 24)
  list_item(:rotating_button, :index => 25)
  list_item(:scrollbars, :index => 26)
  list_item(:search_view, :index => 27)
  list_item(:secure_view, :index => 28)
  list_item(:seek_bar, :index => 29)
  list_item(:spinner, :index => 30)
  list_item(:splitting_touches_across_views, :index => 31)
  list_item(:switches, :index => 32)
  list_item(:tabs, :index => 33)
  list_item(:text_switcher, :index => 34)
  list_item(:visibility, :index => 35)
  list_item(:webview, :index => 36)
end
